### ISSUE TITLE
以管理员身份运行时，无法拖入文件、快捷方式

### ISSUE THREAD

**Issue by LadyPumie** [XIU2/TileTool#1]
v4.0.2版本在非管理员身份运行时，拖入磁贴/快捷方式可以正常运行，管理员身份运行时拖入磁贴/快捷方式无反应。

**Comment by XIU2** [comment]
啊，才看到...  
该 BUG 昨天(v4.0.3)已经修复了。

****

> 奇怪，Github 怎么突然不给我发 Issues 邮件通知了。。。
