### ISSUE TITLE
关于磁贴显示文件名字体颜色的问题

### ISSUE THREAD

**Issue by wstarrysky** [XIU2/TileTool#12]
使用的时候发现有时候磁贴上文件名字体颜色是黑色,有时候又是白色,这好像并不可控.这个可以优化的嘛?
然后还有一个建议就是添加一个照片剪裁的脚本在压缩包里面,把一张照片直接按比例裁剪.

**Comment by XIU2** [comment]
磁贴名称颜色取决于背景颜色深浅。
裁剪图片功能不会添加，一个是我不熟，一个是 Win11 已经移除磁贴功能了，所以这个软件基本上不会再更新了。

**Comment by XIU2** [comment]
准确的说，磁贴名称颜色以前是可以自定义的，但是 Win10 2004 启用新版磁贴样式后，就改为强制自适应了（根据磁贴背景颜色），已经无法自定义了。

**Comment by wstarrysky** [comment]
我有写过一个裁剪图片的脚本,但是git的拉取不太会操作,觉得这个挺适合操作想要一张整图片作为一个磁贴组背景的.但是我不知道怎么提交给你,有邮箱或者其他也可。

**Comment by wstarrysky** [comment]
> 准确的说，磁贴名称颜色以前是可以自定义的，但是 Win10 2004 启用新版磁贴样式后，就改为强制自适应了（根据磁贴背景颜色），已经无法自定义了。



> 磁贴名称颜色取决于背景颜色深浅。 裁剪图片功能不会添加，一个是我不熟，一个是 Win11 以及移除磁贴功能了，所以这个软件基本上不会再更新了。

我有写过一个裁剪图片的脚本,但是git的拉取不太会操作,觉得这个挺适合操作想要一张整图片作为一个磁贴组背景的.但是我不知道怎么提交给你,有邮箱或者其他也可。

**Comment by wstarrysky** [comment]
> 磁贴名称颜色取决于背景颜色深浅。 裁剪图片功能不会添加，一个是我不熟，一个是 Win11 以及移除磁贴功能了，所以这个软件基本上不会再更新了。

应该放在蓝奏云的发布包里就好了。（话说大佬这个真的好用   ahah，i like it）
