### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Himalian** [XIU2/TileTool#14]
右键单击可以设置主题色，但较早的Windows 10版本中，直接确认更改后会使得磁贴背景恢复灰色（或者白色），而需要重新选取背景色后才能保持更改（其实不是什么严重的bug，但是有点麻烦233333）

**Comment by Butterblock233** [comment]
右键单击可以设置主题色，但较早的Windows 10版本中，直接确认更改后会使得磁贴背景恢复灰色（或者白色），而需要重新选取背景色后才能保持更改（其实不是什么严重的bug，但是有点麻烦233333）

**Comment by XIU2** [comment]
https://zhuanlan.zhihu.com/p/79630122 里写了 `· UWP 应用 如何自定义磁贴样式？·` 方法。

**Comment by XIU2** [comment]
关于背景色，自从 Win10 2004 改用**新版磁贴样式**后，就无法自定义磁贴的背景颜色了（所有磁贴背景颜色统一为系统主题色），因此我就将其取消了（当时正好是重写软件，因此设计的时候就没有留下自定义背景颜色的功能），但后来还有少数用 Win10 旧版系统的人希望恢复这个功能，于是我给加到右键里让他们凑活着用了。

不过 Win11 已经移除了磁贴，因此这个软件估计是不会再更新了。

**Comment by Himalian** [comment]
> https://zhuanlan.zhihu.com/p/79630122 里写了 `· UWP 应用 如何自定义磁贴样式？·` 方法。

刚刚教程没看到完，把UWP的快捷方式直接用磁贴美化小工具打开了，所以就出了问题😂😂
