### ISSUE TITLE
删除软件后右键菜单内的残留项如何清理

### ISSUE THREAD

**Issue by Cherisss** [XIU2/TileTool#16]
通过多种方法包括检查注册表、第三方工具等都无法找到该项
![image](https://user-images.githubusercontent.com/72339270/227766429-a40a8296-6987-4a7a-bdf5-55036233a64d.png)

**Comment by XIU2** [comment]
删除软件前，以管理员身份打开软件点击左下角的 [添加右键菜单] 按钮（即关闭该功能），软件就会帮你删了注册表。
然后你再去删除软件。
