### ISSUE TITLE
导入 [开启 2004 新版磁贴.reg] 后，开始菜单出现 [关键错误，你的开始菜单出现了问题...]

### ISSUE THREAD

**Issue by EzakiRinko** [XIU2/TileTool#2]
![21](https://user-images.githubusercontent.com/67503875/94331136-b3468f80-ffb9-11ea-8503-16df41f574c4.png)
xiu哥咋办呀我不想重装系统

**Comment by XIU2** [comment]
回答下列问题：  
- 你是否满足了前置条件（2004+可选补丁）？  
- 重启后还会出现这种错误吗？  
- 开机后就直接弹出该错误吗？  
- 弹出该错误后无法进行其他操作吗？

**Comment by EzakiRinko** [comment]
> 回答下列问题：
> 
> * 你是否满足了前置条件（2004+可选补丁）？
> * 重启后还会出现这种错误吗？
> * 开机后就直接弹出该错误吗？
> * 弹出该错误后无法进行其他操作吗？

我是2004最新版本  
重启后还会错误
开机后点开始菜单才会弹出
弹出后可以进行其他操作 只是菜单 个性化等界面打不开

**Comment by EzakiRinko** [comment]
导入  关闭 2004 新版磁贴.reg  后  关键错误依然存在

**Comment by XIU2** [comment]
设置 - 系统 - 关于 - 操作系统版本，你的版本号是多少？（19041.XXX）
另外你看一下注册表：
计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion 中 CurrentVersion 的值是什么。

**Comment by XIU2** [comment]
才想起来你是看不到新版设置界面的。。。  
那你也没办法看操作系统版本，只有安装可选补丁后版本号才会大于或等于 19041。  
你确定安装了最新的可选更新补丁吗？

**Comment by EzakiRinko** [comment]
> 设置 - 系统 - 关于 - 操作系统版本

打不开设置界面

![image](https://user-images.githubusercontent.com/67503875/94331397-84311d80-ffbb-11ea-8562-173653efb816.png)

![image](https://user-images.githubusercontent.com/67503875/94331437-cc504000-ffbb-11ea-8cd8-32f28b5514f5.png)

**Comment by EzakiRinko** [comment]
> 才想起来你是看不到新版设置界面的。。。
> 那你也没办法看操作系统版本，只有安装可选补丁后版本号才会大于或等于 19041。
> 你确定安装了最新的可选更新补丁吗？

我确定安装了最新的可选更新补丁

**Comment by XIU2** [comment]
开启新版磁贴实际上就是添加了一个注册表项：  
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\0\2093230218  

关闭新版磁贴实际上就是删除了这个注册表项。    
****
你试过网上说的那个修改 User Manger 服务的方法吗？

**Comment by EzakiRinko** [comment]
> 开启新版磁贴实际上就是添加了一个注册表项：
> 
> > HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\0\2093230218
> 
> 关闭新版磁贴实际上就是删除了这个注册表项。
> 
> 你试过网上说的那个修改 User Manger 服务的方法吗？

我的User Manger服务是打开的

**Comment by EzakiRinko** [comment]
> 开启新版磁贴实际上就是添加了一个注册表项：
> 
> > HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\0\2093230218
> 
> 关闭新版磁贴实际上就是删除了这个注册表项。
> 
> 你试过网上说的那个修改 User Manger 服务的方法吗？

删除该项后并重启 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\0\2093230218 关键错误依然存在

**Comment by XIU2** [comment]
User Manger服务右键 - 属性，截图我看看。

注册表这个有点迷啊，添加注册表后报错，删除注册表后还报错。。。你添加注册表时是不是还做了其他的事情？

这个注册表是开启隐藏功能的，让用户选择性体验的，下个版本中微软就默认开启这些功能了（好像是 20H2）。

**Comment by EzakiRinko** [comment]
![image](https://user-images.githubusercontent.com/67503875/94331710-69ac7380-ffbe-11ea-800e-24e6ceeb703d.png)

**Comment by EzakiRinko** [comment]
> User Manger服务右键 - 属性，截图我看看。
> 
> 注册表这个有点迷啊，添加注册表后报错，删除注册表后还报错。。。你添加注册表时是不是还做了其他的事情？
> 
> 这个注册表是开启隐藏功能的，让用户选择性体验的，下个版本中微软就默认开启这些功能了（好像是 20H2）。

我第一次导入注册表 是在压缩包中直接双击导入的 不知道是不是这个原因

**Comment by XIU2** [comment]
> 我第一次导入注册表 是在压缩包中直接双击导入的 不知道是不是这个原因

没有区别，不是这个问题。

**Comment by XIU2** [comment]
你试过这个方法没有？  

按下 Win+R 键，输入 `powershell` 并回车  ，然后执行下面的代码，完成后重启电脑。  

``` powershell
# 下面代码指的是重装 Win10 所有内置应用（包括开始菜单、设置等）。

Get-AppxPackage | % { Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppxManifest.xml" -verbose }

# 或（上面是当前用户，下面是所有用户，你先执行上面的看看重启后是否正常，还不行再试试下面这个）

Get-AppxPackage -AllUsers| Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
```

> 来自：https://zhidao.baidu.com/question/1437456362848389539.html

**Comment by EzakiRinko** [comment]
> 你试过这个方法没有？
> 
> 按下 Win+R 键，输入 `powershell` 并回车 ，然后执行下面的代码，完成后重启电脑。
> 
> ```powershell
> # 下面代码指的是重装 Win10 所有内置应用（包括开始菜单、设置等）。
> 
> Get-AppxPackage | % { Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppxManifest.xml" -verbose }
> 
> # 或（上面是当前用户，下面是所有用户，你先执行上面的看看重启后是否正常，还不行再试试下面这个）
> 
> Get-AppxPackage -AllUsers| Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
> ```
> 
> > 来自：https://zhidao.baidu.com/question/1437456362848389539.html

谢谢大佬  还没重启菜单就好了

**Comment by XIU2** [comment]
那就好，如果没有其他问题的话就关闭该 Issues 吧。
我会把这个 Issues 加到开启新版磁贴说明.txt 中。

**Comment by EzakiRinko** [comment]
> 那就好，如果没有其他问题的话就关闭该 Issues 吧。
> 我会把这个 Issues 加到开启新版磁贴说明.txt 中。

好的，谢谢。
