### ISSUE TITLE
求定期备份排版的功能

### ISSUE THREAD

**Issue by littlegolden** [XIU2/TileTool#6]
定期备份开始菜单排版，可以避免操作失误（误删注册表等）导致开始菜单被系统重置为出厂设置。血的教训

**Comment by XIU2** [comment]
问题是我根本不知道开始菜单排版储存在哪里。

**Comment by littlegolden** [comment]
不知这个是否有帮助 https://github.com/TurboLabIt/StartTileBackup

**Comment by XIU2** [comment]
既然已经有现成的备份脚本了，你直接用就行了呀。

或者你把这个脚本加到系统自带的**任务计划**中定期执行（`Win+R` 运行 - `taskschd.msc`）。

****

当然我没有测试过该脚本，如果已经失效了（毕竟如果没失效，你也不会开这个 Issues），说明这几年时间 Win10 对这方面已经产生了变动，那也没什么参考价值了。。。

> 我也去脚本里的文件夹和注册表里看了，但是我也看不出什么东西。。。

**Comment by littlegolden** [comment]
脚本还能用，开 issue 的原因就是觉得备份功能对于美化菜单的用户来说是很有用的，也应该是有需求的，如果加上这个功能，用户体验会更好哈哈哈

**Comment by XIU2** [comment]
emmm 这几年了，除了你之外，没有其他人提过类似的需求。。。

**Comment by littlegolden** [comment]
估计把开始菜单搞崩的几率还是挺小的吧

**Comment by XIU2** [comment]
那我就把这个脚本汉化一下，放到我的网盘里（就是磁贴美化小工具的分享链接中），有人需要的话就自取。

已经上传到网盘中了，你可以去看看：https://xiu.lanzoux.com/b0sp46eh
