### ISSUE TITLE
通过修改注册表改回了旧版磁贴，但是软件不能开启取色，能不能更新一个手动开启取色的开关呢？

### ISSUE THREAD

**Issue by 2ciyv** [XIU2/TileTool#9]
根据知乎https://www.zhihu.com/question/450865391 的回复里的内容修改了注册表让磁贴回到旧版，但是软件不能开启取色，能不能更新一个手动开启取色的开关呢？

**Comment by XIU2** [comment]
已经更新了。

## 2021年07月21日，版本 v4.1.0
1. **新增** 旧版磁贴模式（开关选项）。
`—— 使用旧版磁贴的电脑，可以开启该选项，就支持自定义背景颜色、屏幕取色等功能了。`
